spring:
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

app:
  jwt:
    # In production, set via env var: APP_JWT_SECRET
    secret: "rq5+dBh7VlSvIZo8x6rteSEy8sI4/oj5jjhHjjNJHpkfeXaRVTHn/jBQq5h6l0RgRBDo8t16+NodQjzO9bw+Pw=="
    issuer: 645545824261147
    expiresMinutes: 43200 # 30 days

cloudinary:
  url: cloudinary://645545824261147:Ag-iwCsQrpD_zMLR2oXShHp4dnY@dwowqg06t
  folder: "food-delivery"
